/* flow */

export const EMAIL_CHANGED = 'EMAIL_CHANGED';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';
export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL';
export const LOGOUT_SUCCESSFUL = 'LOGOUT_SUCCESSFUL';
export const AUTH_TOKEN_RECEIVED = 'AUTH_TOKEN_RECEIVED';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';
export const LOGIN_USER = 'LOGIN_USER';

export const REGISTER_SEND = 'REGISTER_SEND';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const USERNAME_CHANGED = 'USERNAME_CHANGED';
